# Generated by Django 3.2.7 on 2021-10-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
