# Generated by Django 3.2.7 on 2021-10-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='待办事项内容')),
                ('remark', models.CharField(max_length=500, verbose_name='备注')),
                ('priority', models.IntegerField(choices=[(1, '低优先级'), (2, '中低优先级'), (3, '中优先级'), (4, '中高优先级'), (5, '高优先级')], default=1, verbose_name='优先级')),
                ('completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建的时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最后一次更新的时间')),
            ],
        ),
    ]
